# Generate expresso_sample_100k dataset
- Generate 100K Sample CSV file from expresso.csv

# Step 1 — Mount Google Drive

**Authorize access when prompted.**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Step 2 — Install & Import Libraries

In [ ]:
# pip install pandas
import pandas as pd

# Step 3 — Define File Paths

In [ ]:
# input_file = "/path/to/expresso.csv"
# output_file = "/path/to/expresso_sample_100k.csv"

# Step 4 - Use Chunk Processing

In [ ]:
input_file_size = 2_000_000 # Approximate number of rows
chunksize = 200_000   # Process 200k rows at a time
target_sample_size = 100_000

In [ ]:
sample_chunks = []

for chunk in pd.read_csv(input_file, chunksize=chunksize):
    sample_chunk = chunk.sample(frac=target_sample_size / input_file_size, random_state=42)
    sample_chunks.append(sample_chunk)

In [ ]:
# Combine all sampled chunks
expresso_sample = pd.concat(sample_chunks)

# Ensure exactly 100k rows
expresso_sample_100k = expresso_sample.sample(n=100_000, random_state=42)

expresso_sample_100k.to_csv(output_file, index=False)

print("expresso_sample_100k dataset created")

expresso_sample_100k dataset created

# Step 5 — Verify the Output

In [ ]:
# path = "/path/to/expresso_sample_100k.csv"

df = pd.read_csv(path)

In [ ]:
df.head()

,user_id,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,MRG,REGULARITY,TOP_PACK,FREQ_TOP_PACK,CHURN
0,22322777e909ae0aa1c69e7b1fce40f333187fa6,DAKAR,K > 24 month,8650.0,37.0,8650.0,2883.0,38.0,2593.0,3.0,39.0,1.0,NaN,NaN,NO,59,"Data: 100 F=40MB,24H",20.0,0
1,453d2b534a53e30171b3c0c72dc7d56415619d8a,NaN,K > 24 month,1000.0,2.0,980.0,327.0,2.0,1362.0,NaN,1.0,9.0,NaN,NaN,NO,8,"Data:490F=1GB,7d",2.0,0
2,9e64b12fd171b51378111bbb1f25242e79c7be99,NaN,K > 24 month,NaN,NaN,NaN,NaN,NaN,1043.0,4.0,NaN,NaN,NaN,NaN,NO,8,NaN,NaN,1
3,369f886e40ef9ec4de23784888d412e5f336cca1,LOUGA,K > 24 month,250.0,1.0,250.0,83.0,2.0,389.0,5.0,NaN,NaN,NaN,NaN,NO,58,"Data: 200 F=100MB,24H",1.0,0
4,3524a53cd138dfe31a2f48c2cc21ed4129df1d10,DAKAR,K > 24 month,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NO,15,NaN,NaN,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   user_id         100000 non-null  object
 1   REGION          60844 non-null   object
 2   TENURE          100000 non-null  object
 3   MONTANT         65059 non-null   float64
 4   FREQUENCE_RECH  65059 non-null   float64
 5   REVENUE         66484 non-null   float64
 6   ARPU_SEGMENT    66484 non-null   float64
 7   FREQUENCE       66484 non-null   float64
 8   DATA_VOLUME     50813 non-null   float64
 9   ON_NET          63663 non-null   float64
 10  ORANGE          58621 non-null   float64
 11  TIGO            40369 non-null   float64
 12  ZONE1           7909 non-null    float64
 13  ZONE2           6493 non-null    float64
 14  MRG             100000 non-null  object
 15  REGULARITY      100000 non-null  int64
 16  TOP_PACK        58264 non-null   object
 17  FREQ_TOP_PACK   58264 non-null   float64
 18  CHURN           100000 non-null  int64
dtypes: float64(12), int64(2), object(5)
memory usage: 14.5+ MB

In [ ]:
df.describe()

,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,REGULARITY,FREQ_TOP_PACK,CHURN
count,65059.000000,65059.000000,66484.000000,66484.000000,66484.000000,50813.000000,63663.000000,58621.000000,40369.000000,7909.000000,6493.000000,100000.000000,58264.000000,100000.000000
mean,5529.499055,11.557725,5508.247443,1836.088187,14.009326,3385.929546,279.007116,94.751335,23.241844,8.098116,7.390574,28.148500,9.295860,0.186550
std,7175.847841,13.306893,7259.055151,2419.680269,14.724153,12533.674332,871.238988,202.436687,64.455804,35.655488,32.271304,22.301885,12.806149,0.389552
min,50.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,1000.000000,2.000000,1000.000000,333.000000,3.000000,0.000000,5.000000,7.000000,2.000000,0.000000,0.000000,6.000000,2.000000,0.000000
50%,3000.000000,7.000000,3000.000000,1000.000000,9.000000,256.000000,27.000000,28.000000,6.000000,1.000000,2.000000,24.000000,5.000000,0.000000
75%,7300.000000,16.000000,7301.000000,2434.000000,20.000000,2927.000000,158.000000,98.000000,20.000000,4.000000,5.000000,51.000000,12.000000,0.000000
max,226550.000000,132.000000,233413.000000,77804.000000,91.000000,926547.000000,36687.000000,5299.000000,1963.000000,1204.000000,1346.000000,62.000000,560.000000,1.000000